%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info
options_ = [];
M_.fname = 'swz_f';
M_.dynare_version = '6.1';
oo_.dynare_version = '6.1';
options_.dynare_version = '6.1';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(4,1);
M_.exo_names_tex = cell(4,1);
M_.exo_names_long = cell(4,1);
M_.exo_names(1) = {'e_q'};
M_.exo_names_tex(1) = {'e\_q'};
M_.exo_names_long(1) = {'e_q'};
M_.exo_names(2) = {'e_a'};
M_.exo_names_tex(2) = {'e\_a'};
M_.exo_names_long(2) = {'e_a'};
M_.exo_names(3) = {'e_t'};
M_.exo_names_tex(3) = {'e\_t'};
M_.exo_names_long(3) = {'e_t'};
M_.exo_names(4) = {'e_r'};
M_.exo_names_tex(4) = {'e\_r'};
M_.exo_names_long(4) = {'e_r'};
M_.endo_names = cell(10,1);
M_.endo_names_tex = cell(10,1);
M_.endo_names_long = cell(10,1);
M_.endo_names(1) = {'x'};
M_.endo_names_tex(1) = {'x'};
M_.endo_names_long(1) = {'x'};
M_.endo_names(2) = {'pi'};
M_.endo_names_tex(2) = {'pi'};
M_.endo_names_long(2) = {'pi'};
M_.endo_names(3) = {'rs'};
M_.endo_names_tex(3) = {'rs'};
M_.endo_names_long(3) = {'rs'};
M_.endo_names(4) = {'rn'};
M_.endo_names_tex(4) = {'rn'};
M_.endo_names_long(4) = {'rn'};
M_.endo_names(5) = {'yn'};
M_.endo_names_tex(5) = {'yn'};
M_.endo_names_long(5) = {'yn'};
M_.endo_names(6) = {'y'};
M_.endo_names_tex(6) = {'y'};
M_.endo_names_long(6) = {'y'};
M_.endo_names(7) = {'qe'};
M_.endo_names_tex(7) = {'qe'};
M_.endo_names_long(7) = {'qe'};
M_.endo_names(8) = {'a'};
M_.endo_names_tex(8) = {'a'};
M_.endo_names_long(8) = {'a'};
M_.endo_names(9) = {'theta'};
M_.endo_names_tex(9) = {'theta'};
M_.endo_names_long(9) = {'theta'};
M_.endo_names(10) = {'v'};
M_.endo_names_tex(10) = {'v'};
M_.endo_names_long(10) = {'v'};
M_.endo_partitions = struct();
M_.param_names = cell(19,1);
M_.param_names_tex = cell(19,1);
M_.param_names_long = cell(19,1);
M_.param_names(1) = {'beta'};
M_.param_names_tex(1) = {'beta'};
M_.param_names_long(1) = {'beta'};
M_.param_names(2) = {'z'};
M_.param_names_tex(2) = {'z'};
M_.param_names_long(2) = {'z'};
M_.param_names(3) = {'sigma'};
M_.param_names_tex(3) = {'sigma'};
M_.param_names_long(3) = {'sigma'};
M_.param_names(4) = {'chi'};
M_.param_names_tex(4) = {'chi'};
M_.param_names_long(4) = {'chi'};
M_.param_names(5) = {'bfi'};
M_.param_names_tex(5) = {'bfi'};
M_.param_names_long(5) = {'bfi'};
M_.param_names(6) = {'bcb'};
M_.param_names_tex(6) = {'bcb'};
M_.param_names_long(6) = {'bcb'};
M_.param_names(7) = {'gamma'};
M_.param_names_tex(7) = {'gamma'};
M_.param_names_long(7) = {'gamma'};
M_.param_names(8) = {'xi'};
M_.param_names_tex(8) = {'xi'};
M_.param_names_long(8) = {'xi'};
M_.param_names(9) = {'rho_r'};
M_.param_names_tex(9) = {'rho\_r'};
M_.param_names_long(9) = {'rho_r'};
M_.param_names(10) = {'rho_a'};
M_.param_names_tex(10) = {'rho\_a'};
M_.param_names_long(10) = {'rho_a'};
M_.param_names(11) = {'rho_theta'};
M_.param_names_tex(11) = {'rho\_theta'};
M_.param_names_long(11) = {'rho_theta'};
M_.param_names(12) = {'rho_q'};
M_.param_names_tex(12) = {'rho\_q'};
M_.param_names_long(12) = {'rho_q'};
M_.param_names(13) = {'rho_v'};
M_.param_names_tex(13) = {'rho\_v'};
M_.param_names_long(13) = {'rho_v'};
M_.param_names(14) = {'phi_pi'};
M_.param_names_tex(14) = {'phi\_pi'};
M_.param_names_long(14) = {'phi_pi'};
M_.param_names(15) = {'phi_x'};
M_.param_names_tex(15) = {'phi\_x'};
M_.param_names_long(15) = {'phi_x'};
M_.param_names(16) = {'s_r'};
M_.param_names_tex(16) = {'s\_r'};
M_.param_names_long(16) = {'s_r'};
M_.param_names(17) = {'s_q'};
M_.param_names_tex(17) = {'s\_q'};
M_.param_names_long(17) = {'s_q'};
M_.param_names(18) = {'s_theta'};
M_.param_names_tex(18) = {'s\_theta'};
M_.param_names_long(18) = {'s_theta'};
M_.param_names(19) = {'s_a'};
M_.param_names_tex(19) = {'s\_a'};
M_.param_names_long(19) = {'s_a'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 4;
M_.endo_nbr = 10;
M_.param_nbr = 19;
M_.orig_endo_nbr = 10;
M_.aux_vars = [];
M_.Sigma_e = zeros(4, 4);
M_.Correlation_matrix = eye(4, 4);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.learnt_shocks = [];
M_.learnt_endval = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
M_.matched_irfs = {};
M_.matched_irfs_weights = {};
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.ramsey_policy = false;
options_.discretionary_policy = false;
M_.eq_nbr = 10;
M_.ramsey_orig_eq_nbr = 0;
M_.ramsey_orig_endo_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 6 16;
 0 7 17;
 1 8 0;
 0 9 0;
 0 10 0;
 0 11 0;
 2 12 18;
 3 13 0;
 4 14 19;
 5 15 0;]';
M_.nstatic = 3;
M_.nfwrd   = 2;
M_.npred   = 3;
M_.nboth   = 2;
M_.nsfwrd   = 4;
M_.nspred   = 5;
M_.ndynamic   = 7;
M_.dynamic_tmp_nbr = [1; 0; 0; 0; ];
M_.equations_tags = {
  1 , 'name' , 'x' ;
  2 , 'name' , 'pi' ;
  3 , 'name' , 'rs' ;
  4 , 'name' , 'rn' ;
  5 , 'name' , 'yn' ;
  6 , 'name' , 'qe' ;
  7 , 'name' , 'y' ;
  8 , 'name' , 'a' ;
  9 , 'name' , 'theta' ;
  10 , 'name' , 'v' ;
};
M_.mapping.x.eqidx = [1 2 3 7 ];
M_.mapping.pi.eqidx = [1 2 3 ];
M_.mapping.rs.eqidx = [1 3 ];
M_.mapping.rn.eqidx = [1 4 ];
M_.mapping.yn.eqidx = [5 7 ];
M_.mapping.y.eqidx = [7 ];
M_.mapping.qe.eqidx = [1 2 6 ];
M_.mapping.a.eqidx = [4 5 8 ];
M_.mapping.theta.eqidx = [1 2 9 ];
M_.mapping.v.eqidx = [3 10 ];
M_.mapping.e_q.eqidx = [6 ];
M_.mapping.e_a.eqidx = [8 ];
M_.mapping.e_t.eqidx = [9 ];
M_.mapping.e_r.eqidx = [10 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.block_structure.time_recursive = false;
M_.block_structure.block(1).Simulation_Type = 1;
M_.block_structure.block(1).endo_nbr = 6;
M_.block_structure.block(1).mfs = 6;
M_.block_structure.block(1).equation = [ 6 8 9 10 5 4];
M_.block_structure.block(1).variable = [ 7 8 9 10 5 4];
M_.block_structure.block(1).is_linear = true;
M_.block_structure.block(1).NNZDerivatives = 12;
M_.block_structure.block(1).bytecode_jacob_cols_to_sparse = [1 2 3 4 7 8 9 10 11 12 ];
M_.block_structure.block(2).Simulation_Type = 8;
M_.block_structure.block(2).endo_nbr = 3;
M_.block_structure.block(2).mfs = 3;
M_.block_structure.block(2).equation = [ 3 1 2];
M_.block_structure.block(2).variable = [ 3 1 2];
M_.block_structure.block(2).is_linear = true;
M_.block_structure.block(2).NNZDerivatives = 11;
M_.block_structure.block(2).bytecode_jacob_cols_to_sparse = [1 4 5 6 8 9 ];
M_.block_structure.block(3).Simulation_Type = 1;
M_.block_structure.block(3).endo_nbr = 1;
M_.block_structure.block(3).mfs = 1;
M_.block_structure.block(3).equation = [ 7];
M_.block_structure.block(3).variable = [ 6];
M_.block_structure.block(3).is_linear = true;
M_.block_structure.block(3).NNZDerivatives = 1;
M_.block_structure.block(3).bytecode_jacob_cols_to_sparse = [2 ];
M_.block_structure.block(1).g1_sparse_rowval = int32([]);
M_.block_structure.block(1).g1_sparse_colval = int32([]);
M_.block_structure.block(1).g1_sparse_colptr = int32([]);
M_.block_structure.block(2).g1_sparse_rowval = int32([1 1 2 1 2 3 1 3 2 2 3 ]);
M_.block_structure.block(2).g1_sparse_colval = int32([1 4 4 5 5 5 6 6 8 9 9 ]);
M_.block_structure.block(2).g1_sparse_colptr = int32([1 2 2 2 4 7 9 9 10 12 ]);
M_.block_structure.block(3).g1_sparse_rowval = int32([]);
M_.block_structure.block(3).g1_sparse_colval = int32([]);
M_.block_structure.block(3).g1_sparse_colptr = int32([]);
M_.block_structure.variable_reordered = [ 7 8 9 10 5 4 3 1 2 6];
M_.block_structure.equation_reordered = [ 6 8 9 10 5 4 3 1 2 7];
M_.block_structure.incidence(1).lead_lag = -1;
M_.block_structure.incidence(1).sparse_IM = [
 3 3;
 6 7;
 8 8;
 9 9;
 10 10;
];
M_.block_structure.incidence(2).lead_lag = 0;
M_.block_structure.incidence(2).sparse_IM = [
 1 1;
 1 3;
 1 4;
 1 7;
 1 9;
 2 1;
 2 2;
 2 7;
 2 9;
 3 1;
 3 2;
 3 3;
 3 10;
 4 4;
 4 8;
 5 5;
 5 8;
 6 7;
 7 1;
 7 5;
 7 6;
 8 8;
 9 9;
 10 10;
];
M_.block_structure.incidence(3).lead_lag = 1;
M_.block_structure.incidence(3).sparse_IM = [
 1 1;
 1 2;
 1 7;
 1 9;
 2 2;
];
M_.block_structure.dyn_tmp_nbr = 0;
M_.state_var = [7 8 9 10 3 ];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(10, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(4, 1);
M_.params = NaN(19, 1);
M_.endo_trends = struct('deflator', cell(10, 1), 'log_deflator', cell(10, 1), 'growth_factor', cell(10, 1), 'log_growth_factor', cell(10, 1));
M_.NNZDerivatives = [38; -1; -1; ];
M_.dynamic_g1_sparse_rowval = int32([3 6 8 9 10 1 2 3 7 2 3 1 3 1 4 5 7 7 1 2 6 4 5 8 1 2 9 3 10 1 1 2 1 1 6 8 9 10 ]);
M_.dynamic_g1_sparse_colval = int32([3 7 8 9 10 11 11 11 11 12 12 13 13 14 14 15 15 16 17 17 17 18 18 18 19 19 19 20 20 21 22 22 27 29 31 32 33 34 ]);
M_.dynamic_g1_sparse_colptr = int32([1 1 1 2 2 2 2 3 4 5 6 10 12 14 16 18 19 22 25 28 30 31 33 33 33 33 33 34 34 35 35 36 37 38 39 ]);
M_.lhs = {
'x'; 
'pi'; 
'rs'; 
'rn'; 
'yn'; 
'qe'; 
'y'; 
'a'; 
'theta'; 
'v'; 
};
M_.static_tmp_nbr = [1; 0; 0; 0; ];
M_.block_structure_stat.block(1).Simulation_Type = 3;
M_.block_structure_stat.block(1).endo_nbr = 1;
M_.block_structure_stat.block(1).mfs = 1;
M_.block_structure_stat.block(1).equation = [ 6];
M_.block_structure_stat.block(1).variable = [ 7];
M_.block_structure_stat.block(2).Simulation_Type = 3;
M_.block_structure_stat.block(2).endo_nbr = 1;
M_.block_structure_stat.block(2).mfs = 1;
M_.block_structure_stat.block(2).equation = [ 8];
M_.block_structure_stat.block(2).variable = [ 8];
M_.block_structure_stat.block(3).Simulation_Type = 3;
M_.block_structure_stat.block(3).endo_nbr = 1;
M_.block_structure_stat.block(3).mfs = 1;
M_.block_structure_stat.block(3).equation = [ 9];
M_.block_structure_stat.block(3).variable = [ 9];
M_.block_structure_stat.block(4).Simulation_Type = 3;
M_.block_structure_stat.block(4).endo_nbr = 1;
M_.block_structure_stat.block(4).mfs = 1;
M_.block_structure_stat.block(4).equation = [ 10];
M_.block_structure_stat.block(4).variable = [ 10];
M_.block_structure_stat.block(5).Simulation_Type = 1;
M_.block_structure_stat.block(5).endo_nbr = 2;
M_.block_structure_stat.block(5).mfs = 2;
M_.block_structure_stat.block(5).equation = [ 5 4];
M_.block_structure_stat.block(5).variable = [ 5 4];
M_.block_structure_stat.block(6).Simulation_Type = 6;
M_.block_structure_stat.block(6).endo_nbr = 3;
M_.block_structure_stat.block(6).mfs = 3;
M_.block_structure_stat.block(6).equation = [ 1 2 3];
M_.block_structure_stat.block(6).variable = [ 3 1 2];
M_.block_structure_stat.block(7).Simulation_Type = 1;
M_.block_structure_stat.block(7).endo_nbr = 1;
M_.block_structure_stat.block(7).mfs = 1;
M_.block_structure_stat.block(7).equation = [ 7];
M_.block_structure_stat.block(7).variable = [ 6];
M_.block_structure_stat.variable_reordered = [ 7 8 9 10 5 4 3 1 2 6];
M_.block_structure_stat.equation_reordered = [ 6 8 9 10 5 4 1 2 3 7];
M_.block_structure_stat.incidence.sparse_IM = [
 1 2;
 1 3;
 1 4;
 2 1;
 2 2;
 2 7;
 2 9;
 3 1;
 3 2;
 3 3;
 3 10;
 4 4;
 4 8;
 5 5;
 5 8;
 6 7;
 7 1;
 7 5;
 7 6;
 8 8;
 9 9;
 10 10;
];
M_.block_structure_stat.tmp_nbr = 0;
M_.block_structure_stat.block(1).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(1).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(1).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(2).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(3).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(3).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(3).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(4).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(4).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(4).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(5).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(5).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(5).g1_sparse_colptr = int32([]);
M_.block_structure_stat.block(6).g1_sparse_rowval = int32([1 3 2 3 1 2 3 ]);
M_.block_structure_stat.block(6).g1_sparse_colval = int32([1 1 2 2 3 3 3 ]);
M_.block_structure_stat.block(6).g1_sparse_colptr = int32([1 3 5 8 ]);
M_.block_structure_stat.block(7).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(7).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(7).g1_sparse_colptr = int32([]);
M_.static_g1_sparse_rowval = int32([2 3 7 1 2 3 1 3 1 4 5 7 7 2 6 4 5 8 2 9 3 10 ]);
M_.static_g1_sparse_colval = int32([1 1 1 2 2 2 3 3 4 4 5 5 6 7 7 8 8 8 9 9 10 10 ]);
M_.static_g1_sparse_colptr = int32([1 4 7 9 11 13 14 16 19 21 23 ]);
M_.params(1) = 0.995;
beta = M_.params(1);
M_.params(2) = 0.33;
z = M_.params(2);
M_.params(3) = 1;
sigma = M_.params(3);
M_.params(4) = 1;
chi = M_.params(4);
M_.params(5) = 0.697;
bfi = M_.params(5);
M_.params(6) = 0.303;
bcb = M_.params(6);
M_.params(7) = 0.0846;
gamma = M_.params(7);
M_.params(8) = 2.4925;
xi = M_.params(8);
M_.params(9) = 0.8;
rho_r = M_.params(9);
M_.params(10) = 0.8;
rho_a = M_.params(10);
M_.params(11) = 0.8;
rho_theta = M_.params(11);
M_.params(12) = 0.8;
rho_q = M_.params(12);
M_.params(13) = 0;
rho_v = M_.params(13);
M_.params(14) = 1.5;
phi_pi = M_.params(14);
M_.params(15) = 0;
phi_x = M_.params(15);
M_.params(16) = 0.01;
s_r = M_.params(16);
M_.params(17) = 0.01;
s_q = M_.params(17);
M_.params(18) = 0.01;
s_theta = M_.params(18);
M_.params(19) = 0.0125;
s_a = M_.params(19);
%
% INITVAL instructions
%
options_.initval_file = false;
oo_.steady_state(1) = 0;
oo_.steady_state(2) = 0;
oo_.steady_state(3) = 0;
oo_.steady_state(4) = 0;
oo_.steady_state(5) = 0;
oo_.steady_state(6) = 0;
oo_.steady_state(7) = 0;
oo_.steady_state(8) = 0;
oo_.steady_state(9) = 0;
oo_.steady_state(10) = 0;
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = M_.params(17);
M_.Sigma_e(2, 2) = M_.params(19);
M_.Sigma_e(3, 3) = M_.params(18);
M_.Sigma_e(4, 4) = M_.params(16);
options_.irf = 40;
options_.order = 1;
var_list_ = {};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'swz_f_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'swz_f_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'swz_f_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'swz_f_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'swz_f_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'swz_f_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'swz_f_results.mat'], 'oo_recursive_', '-append');
end
if exist('options_mom_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'swz_f_results.mat'], 'options_mom_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
